### PR TITLE
README: add AWS ref architectures

### PR DESCRIPTION
**Pull request by philips**

### CODE REVIEW

**Comment by philips** [comment]
@lxpollitt screenshot? I don't see it.

**Comment by Krylon360** [comment]
Looks like the encoding type may have been set to ASCII vs UTF8 when it was
saved.
Screenshot attached.


Bryce Walter

On Jan 5, 2017 11:19 PM, "Brandon Philips" <notifications@github.com> wrote:

@lxpollitt <https://github.com/lxpollitt> screenshot? I don't see it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/projectcalico/canal/pull/29#issuecomment-270840102>,
or mute
the thread

**Comment by philips** [comment]
@lxpollitt @Krylon360 fixed, I think.

**Comment by gunjan5** [comment]
@philips still see 2 weird characters at one more place in the final github rendered view. See the screenshot: http://www.screencast.com/t/K9klORRC1
Seems like the `[` is getting replaced by `â`

**Comment by lxpollitt** [comment]
I think I fixed up the last character encoding issues.  I'm going to merge.  We can make further improvements in subsequent PRs, but I don't want to delay this PR further.

**Pull request merged**
