### PR TITLE
remove namespace from ClusterRoleBinding specs

### PR DESCRIPTION
**Pull request by davemac30**

### CODE REVIEW

**Comment by caseydavenport** [comment]
@davemac30 could you add some context for these changes to the description? 

Why do we want to remove the namespace?

**Comment by davemac30** [comment]
Because ClusterRoleBinding is not namespaced:
```
$ kubectl get clusterrolebindings --all-namespaces
NAMESPACE   NAME      AGE
error: clusterRoleBinding is not namespaced
```

It doesn't cause an error when using kubectl create - I'm guessing it just gets silently ignored, but...

I created a script to process these manifests and convert them to ansible code which posts to the API using the ansible uri module. The script chooses the API path to post to depending (amongst other things) on the presence of the namespace in the metadata. The clusterrolebindings in the canal manifests fail for this reason.

**Comment by caseydavenport** [comment]
Hm, good point! 

Yeah, I guess kubectl is just ignoring that since it's not a namespaced resource (which sounds like a bug in itself).

**Comment by caseydavenport** [comment]
Thanks for the fix - we'll need to make sure we apply this change to the upstream Calico manifests as well.


Looks like the CLA bot isn't happy - have you signed the CLA?

**Comment by davemac30** [comment]
I did earlier today, so maybe it takes a little time...

**Comment by tmjd** [comment]
The commit says it is from davemcneill instead of davemac30, that might be why it isn't showing as signed.  I think you might need to make sure the Author of the commit is the same as what is associated with your github account.

**Comment by davemac30** [comment]
Sorry about that - I used git config for our internal github enterprise when I committed. I've closed this and I'll resubmit with a proper author.

**Pull request closed without merging**
